/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DomainModel.HoaDon;
import DomainModel.HoaDonChiTiet;
import Service.ServiceImpl.BanHangServiceimpl;
import ViewModel.ChiTietDienThoaiViewModel;
import ViewModel.DienThoaiViewModel;
import ViewModel.HoaDonChiTietViewModel;
import ViewModel.ViewModelHoaDon;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class BanHangView extends javax.swing.JFrame {

    private DefaultTableModel dtmSP = new DefaultTableModel();
    private DefaultTableModel dtmDonHang = new DefaultTableModel();
    private DefaultTableModel dtmHoaDonChuaThanhToan = new DefaultTableModel();
    private DefaultComboBoxModel dcbmKhachHang = new DefaultComboBoxModel();
    private DefaultComboBoxModel dcbmNV = new DefaultComboBoxModel();
    private DefaultComboBoxModel dcbmMaGG = new DefaultComboBoxModel();
    private DefaultComboBoxModel dcbmMaHD = new DefaultComboBoxModel();
    private List<DienThoaiViewModel> listDienThoai = new ArrayList<>();
    private List<HoaDon> listHoaDonChuaThanhToan = new ArrayList<>();
    private List<HoaDonChiTietViewModel> listHoaDonCT = new ArrayList<HoaDonChiTietViewModel>();
    private List<String> listKhachHang = new ArrayList<>();
    private List<String> listNhanVien = new ArrayList<>();
    private List<String> listMaGG = new ArrayList<>();
    private BanHangServiceimpl bhs = new BanHangServiceimpl();

    /**
     * Creates new form BanHangView
     */
    public BanHangView() {
        initComponents();
        tbSanPhamBanHang.setModel(dtmSP);
        tbDonHangBanHang.setModel(dtmDonHang);
        tbHoaDonChuaThanhToan.setModel(dtmHoaDonChuaThanhToan);
        cbbKhachHangBanHang.setModel(dcbmKhachHang);
        cbbMaNhanVien.setModel(dcbmNV);
        cbbMaGGBanHang.setModel(dcbmMaGG);
        String[] header1 = {"Mã SP", "Tên SP", "Giá"};
        dtmSP.setColumnIdentifiers(header1);
        String[] header2 = {"IMEI", "Tên SP", "Giá"};
        dtmDonHang.setColumnIdentifiers(header2);
        String[] header3 = {"Mã hóa đơn"};
        dtmHoaDonChuaThanhToan.setColumnIdentifiers(header3);
        bhs.getAllHoaDonChuaThanhToan(listHoaDonChuaThanhToan);
        bhs.showDataHoaDonChuaThanhToan(dtmHoaDonChuaThanhToan, listHoaDonChuaThanhToan);
        bhs.getAll(listDienThoai);
        bhs.showData(dtmSP, listDienThoai);
        bhs.getTenKH(listKhachHang);
        dcbmKhachHang.addAll(listKhachHang);
        bhs.getMaNV(listNhanVien);
        dcbmNV.addAll(listNhanVien);
        bhs.getMaGG(listMaGG);
        dcbmMaGG.addAll(listMaGG);
        bhs.sapXepHoaDon(listHoaDonChuaThanhToan);
        bhs.showDataHoaDonChuaThanhToan(dtmHoaDonChuaThanhToan, listHoaDonChuaThanhToan);
        cbbKhachHangBanHang.setSelectedIndex(0);
        cbbMaGGBanHang.setSelectedIndex(0);
        cbbMaNhanVien.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiemSPBanHang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSapXepThapCaoBanHang = new javax.swing.JButton();
        btnSapXepCaoThapBanHang = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSanPhamBanHang = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbDonHangBanHang = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        cbbKhachHangBanHang = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbbMaGGBanHang = new javax.swing.JComboBox<>();
        btnThanhToan = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbTongTien = new javax.swing.JLabel();
        lbGiamGia = new javax.swing.JLabel();
        lbThanhTien = new javax.swing.JLabel();
        btnTaoHoaDon = new javax.swing.JButton();
        btnXoaKhoiHoaDon = new javax.swing.JButton();
        cbbMaNhanVien = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbHoaDonChuaThanhToan = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        lbmaHDDuocChon = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbIMEIDaChon = new javax.swing.JLabel();
        btnThemThongTin = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnShowAll = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnTrangChu = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setText("Tìm kiếm sản phẩm");

        jLabel3.setText("Sắp xếp theo giá");

        btnSapXepThapCaoBanHang.setText("Thấp đên cao");
        btnSapXepThapCaoBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepThapCaoBanHangActionPerformed(evt);
            }
        });

        btnSapXepCaoThapBanHang.setText("Cao đến thấp");
        btnSapXepCaoThapBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepCaoThapBanHangActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("Sản phẩm chi tiết");

        tbSanPhamBanHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbSanPhamBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSanPhamBanHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSanPhamBanHang);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("Đơn hàng");

        tbDonHangBanHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbDonHangBanHang);

        jLabel6.setText("Khách hàng");

        cbbKhachHangBanHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Nhân Viên");

        jLabel10.setText("Chọn mã giảm giá");

        cbbMaGGBanHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbMaGGBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMaGGBanHangActionPerformed(evt);
            }
        });

        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        jLabel11.setText("Hóa đơn");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setText("Tổng tiền");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setText("Giảm giá");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 51));
        jLabel14.setText("Thành tiền");

        lbTongTien.setText("0");

        lbGiamGia.setText("0");

        lbThanhTien.setText("0");

        btnTaoHoaDon.setText("Tạo hóa đơn");
        btnTaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoHoaDonActionPerformed(evt);
            }
        });

        btnXoaKhoiHoaDon.setText("Xóa khỏi hóa đơn");
        btnXoaKhoiHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKhoiHoaDonActionPerformed(evt);
            }
        });

        cbbMaNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tbHoaDonChuaThanhToan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbHoaDonChuaThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHoaDonChuaThanhToanMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbHoaDonChuaThanhToan);

        jLabel15.setText("Hóa đơn chưa thanh toán");

        lbmaHDDuocChon.setText("null");

        jLabel16.setText("Imei đã chọn");

        lbIMEIDaChon.setText("null");

        btnThemThongTin.setText("Thêm thông tin vào hóa đơn");
        btnThemThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemThongTinActionPerformed(evt);
            }
        });

        btnKhachHang.setText("Form khách hàng");
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        btnShowAll.setText("Xem tất cả");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnTrangChu.setText("Trang chủ");
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lbmaHDDuocChon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(273, 273, 273)
                        .addComponent(btnXoaKhoiHoaDon))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)
                        .addGap(38, 38, 38)
                        .addComponent(lbIMEIDaChon, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtTimKiemSPBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTimKiem)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(btnShowAll)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                        .addComponent(btnSapXepThapCaoBanHang)))
                                .addGap(18, 18, 18)
                                .addComponent(btnSapXepCaoThapBanHang))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(cbbKhachHangBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(cbbMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(18, 18, 18)
                                                .addComponent(cbbMaGGBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbGiamGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbThanhTien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnTaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnThemThongTin)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addGap(14, 14, 14)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cbbMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbMaGGBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lbTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lbGiamGia))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lbThanhTien))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemThongTin)
                            .addComponent(btnTaoHoaDon))
                        .addGap(18, 18, 18)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnKhachHang)
                .addGap(18, 18, 18)
                .addComponent(btnTrangChu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiemSPBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSapXepThapCaoBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSapXepCaoThapBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem)
                    .addComponent(cbbKhachHangBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lbIMEIDaChon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnXoaKhoiHoaDon)
                    .addComponent(lbmaHDDuocChon))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(759, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSapXepCaoThapBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepCaoThapBanHangActionPerformed
        // TODO add your handling code here:
        bhs.sapXepTheoGiaGiamDan(listDienThoai);
        bhs.showData(dtmSP, listDienThoai);
    }//GEN-LAST:event_btnSapXepCaoThapBanHangActionPerformed

    private void btnXoaKhoiHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKhoiHoaDonActionPerformed
        // TODO add your handling code here:
        int row = tbDonHangBanHang.getSelectedRow();
        int row1 = tbHoaDonChuaThanhToan.getSelectedRow();
        bhs.deleteHDCT(listHoaDonCT.get(row).getIMEI(), lbmaHDDuocChon.getText());
        resetHoaDonChiTiet(lbmaHDDuocChon.getText());
        thayDoiTien();
    }//GEN-LAST:event_btnXoaKhoiHoaDonActionPerformed

    private void btnTaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoHoaDonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, bhs.addHD());
        resetHoaDonChuaThanhToan();
        bhs.sapXepHoaDon(listHoaDonChuaThanhToan);
        bhs.showDataHoaDonChuaThanhToan(dtmHoaDonChuaThanhToan, listHoaDonChuaThanhToan);
    }//GEN-LAST:event_btnTaoHoaDonActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:

        int row = tbHoaDonChuaThanhToan.getSelectedRow();
        String tenKH = String.valueOf(cbbKhachHangBanHang.getSelectedItem());
        String maNV = String.valueOf(cbbMaNhanVien.getSelectedItem());
        //String maKM = String.valueOf(cbbMaGGBanHang.getSelectedItem());
        String maKM = String.valueOf(cbbMaGGBanHang.getSelectedItem()).substring(0, 5);
        
        JOptionPane.showMessageDialog(rootPane, bhs.thanhToan(tenKH, maNV, maKM, listHoaDonChuaThanhToan.get(row).getMaHoaDon()));
        listHoaDonCT.removeAll(listHoaDonCT);
        bhs.getHDCT(listHoaDonCT, lbmaHDDuocChon.getText());
        for(HoaDonChiTietViewModel a:listHoaDonCT){
            bhs.thayDoiTrangThaiDienThoai(a.getIMEI());
            bhs.xoaSPDaCoTrongHD(a.getIMEI(), listHoaDonChuaThanhToan.get(row).getMaHoaDon());
        }
        resetHoaDonChuaThanhToan();
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void cbbMaGGBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMaGGBanHangActionPerformed
        // TODO add your handling code here:
        thayDoiTien();
    }//GEN-LAST:event_cbbMaGGBanHangActionPerformed

    private void tbHoaDonChuaThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHoaDonChuaThanhToanMouseClicked
        // TODO add your handling code here:
        int row = tbHoaDonChuaThanhToan.getSelectedRow();
        HoaDon a = listHoaDonChuaThanhToan.get(row);
        lbmaHDDuocChon.setText(a.getMaHoaDon());
        bhs.getHDCT(listHoaDonCT, a.getMaHoaDon());
        bhs.showDataHoaDon(dtmDonHang, listHoaDonCT);
        fillThongTin(row);
        resetHoaDonChiTiet(lbmaHDDuocChon.getText());
        thayDoiTien();
    }//GEN-LAST:event_tbHoaDonChuaThanhToanMouseClicked

    private void tbSanPhamBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSanPhamBanHangMouseClicked
        // TODO add your handling code here:
        int row = tbSanPhamBanHang.getSelectedRow();
        int row1 = tbHoaDonChuaThanhToan.getSelectedRow();
        ChonIMEIView detail1 = new ChonIMEIView(this, rootPaneCheckingEnabled, listDienThoai.get(row).getMaDienThoai());
        detail1.setVisible(true);
        lbIMEIDaChon.setText(detail1.layIMEI());
        List<HoaDonChiTietViewModel> lista=new ArrayList<>();
        bhs.checkTrungIMEI(lbmaHDDuocChon.getText(), lbIMEIDaChon.getText(), lista);
        if(lista.size() > 0){
            JOptionPane.showMessageDialog(rootPane, "IMEI này đã có trong hóa đơn");
        }else{
            bhs.addVaoHDCT(lbIMEIDaChon.getText(), lbmaHDDuocChon.getText());
        }
        resetHoaDonChiTiet(lbmaHDDuocChon.getText());
        thayDoiTien();
    }//GEN-LAST:event_tbSanPhamBanHangMouseClicked

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        // TODO add your handling code here:
        KhachHangViewNhanVien detail1 = new KhachHangViewNhanVien();
        this.dispose();
        detail1.setVisible(true);
        
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnThemThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemThongTinActionPerformed
        // TODO add your handling code here:
        String tenKH = String.valueOf(cbbKhachHangBanHang.getSelectedItem());
        String maNV = String.valueOf(cbbMaNhanVien.getSelectedItem());
        JOptionPane.showMessageDialog(rootPane, bhs.themThongTinVaoHD(tenKH, maNV, lbmaHDDuocChon.getText()));   
    }//GEN-LAST:event_btnThemThongTinActionPerformed

    private void btnSapXepThapCaoBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepThapCaoBanHangActionPerformed
        // TODO add your handling code here:
        bhs.sapXepTheoGiaTangDan(listDienThoai);
        bhs.showData(dtmSP, listDienThoai);
    }//GEN-LAST:event_btnSapXepThapCaoBanHangActionPerformed

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        // TODO add your handling code here:
        resetSanPhamChiTiet();
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        listDienThoai.removeAll(listDienThoai);
        bhs.timTen(listDienThoai, txtTimKiemSPBanHang.getText());
        bhs.showData(dtmSP, listDienThoai);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnTrangChuActionPerformed
    public void thayDoiTien() {
        String maHD = lbmaHDDuocChon.getText();
        String maGG = String.valueOf(cbbMaGGBanHang.getSelectedItem()).substring(0, 5);
        int tongTien = bhs.layGiaHD(maHD);
        int giamGia = 0;

        if (bhs.layDonVi(maGG) == true) {
            giamGia = bhs.layGiaGiamGiaK(maGG);
        } else if (bhs.layDonVi(maGG) == false) {
            giamGia = bhs.layGiaGiamGiaPhanTram(tongTien, maGG);
        }
        int thanhTien = bhs.layGiaThanhTien(tongTien, giamGia);
        lbTongTien.setText(String.valueOf(tongTien));
        lbGiamGia.setText(String.valueOf(giamGia));
        lbThanhTien.setText(String.valueOf(thanhTien));

    }

    public void resetSanPhamChiTiet() {
        listDienThoai.removeAll(listDienThoai);
        bhs.getAll(listDienThoai);
        bhs.showData(dtmSP, listDienThoai);
    }

    public void resetHoaDonChiTiet(String maHD) {
        listHoaDonCT.removeAll(listHoaDonCT);
        bhs.getHDCT(listHoaDonCT, maHD);
        bhs.showDataHoaDon(dtmDonHang, listHoaDonCT);
    }

    public void resetHoaDonChuaThanhToan() {
        listHoaDonChuaThanhToan.removeAll(listHoaDonChuaThanhToan);
        bhs.getAllHoaDonChuaThanhToan(listHoaDonChuaThanhToan);
        bhs.showDataHoaDonChuaThanhToan(dtmHoaDonChuaThanhToan, listHoaDonChuaThanhToan);
    }
    
    public void fillThongTin(int index){
        HoaDon a=listHoaDonChuaThanhToan.get(index);
        cbbMaNhanVien.setSelectedItem(a.layMaNV());
        cbbKhachHangBanHang.setSelectedItem(a.layTenKH());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BanHangView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnSapXepCaoThapBanHang;
    private javax.swing.JButton btnSapXepThapCaoBanHang;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JButton btnTaoHoaDon;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThemThongTin;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JButton btnXoaKhoiHoaDon;
    private javax.swing.JComboBox<String> cbbKhachHangBanHang;
    private javax.swing.JComboBox<String> cbbMaGGBanHang;
    private javax.swing.JComboBox<String> cbbMaNhanVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbGiamGia;
    private javax.swing.JLabel lbIMEIDaChon;
    private javax.swing.JLabel lbThanhTien;
    private javax.swing.JLabel lbTongTien;
    private javax.swing.JLabel lbmaHDDuocChon;
    private javax.swing.JTable tbDonHangBanHang;
    private javax.swing.JTable tbHoaDonChuaThanhToan;
    private javax.swing.JTable tbSanPhamBanHang;
    private javax.swing.JTextField txtTimKiemSPBanHang;
    // End of variables declaration//GEN-END:variables
}
