/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DomainModel.KhachHang;
import Service.KhachHangService;
import Service.ServiceImpl.KhachHangServiceImpl;
import ViewModel.KhachHangViewModel;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quan l
 */
public class KhachHangViewQuanLy extends javax.swing.JFrame {

    /**
     * Creates new form KhachHangView
     */
    private DefaultTableModel dtm = new DefaultTableModel();
    private List<KhachHang> listKhachHang = new ArrayList<>();
    private List<KhachHangViewModel> listKhachHangView = new ArrayList<>();
    private List<KhachHangViewModel> listKhachHangView1 = new ArrayList<>();
    private List<KhachHangViewModel> listSearchTen = new ArrayList<>();
    private List<KhachHangViewModel> listSearch = new ArrayList<>();
    private List<KhachHangViewModel> listSearchDiaChi = new ArrayList<>();
    private KhachHangService service = new KhachHangServiceImpl();
    private List<KhachHangViewModel> listSearchSDT = new ArrayList<>();
    int rowOffset = 0;
    int fetch = 5;
    String name = "";
    int index = 0;
    int o = 0;

    public KhachHangViewQuanLy() {
        initComponents();
        tbQuanLyKhachHang.setModel(dtm);
        String header[] = {"Ten", "Ngay sinh", "So dien thoai", "Dia chi", "Email"};
        dtm.setColumnIdentifiers(header);
        listKhachHangView = service.getAllKhachHang(rowOffset);
        service.showDataTable(dtm, listKhachHangView);
        System.out.println(rowOffset);
        o = service.getAllKhachHang1().size() / fetch;
        loadSoTrang();
    }

    private void loadSoTrang() {
        lbls.setText(index + 1 + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgGender = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btAdd = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        txtValidateName = new javax.swing.JLabel();
        txtValidate2 = new javax.swing.JLabel();
        txtValidate3 = new javax.swing.JLabel();
        txtValidate4 = new javax.swing.JLabel();
        txtValidate5 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbbSearch = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbQuanLyKhachHang = new javax.swing.JTable();
        btNext = new javax.swing.JButton();
        btBack = new javax.swing.JButton();
        btBackFirst = new javax.swing.JButton();
        btBackEnd = new javax.swing.JButton();
        lbls = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("QUAN LY KHACH HANG");

        btAdd.setText("Them");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btEdit.setText("Sua");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Tên");

        txtTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenKeyReleased(evt);
            }
        });

        jLabel4.setText("ID:");

        jLabel2.setText("Ngay sinh");

        txtNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySinhActionPerformed(evt);
            }
        });
        txtNgaySinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNgaySinhKeyPressed(evt);
            }
        });

        jLabel6.setText("So dien thoai");

        txtSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSDTKeyReleased(evt);
            }
        });

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        jLabel7.setText("Email");

        jLabel5.setText("Dia chi");

        txtDiaChi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiaChiKeyReleased(evt);
            }
        });

        txtValidate3.setText(" ");

        txtValidate4.setText(" ");

        txtValidate5.setText(" ");

        id.setText("jLabel8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTen, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                            .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(txtEmail))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValidate2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtValidate5, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValidate3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(13, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtValidate4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtDiaChi)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtValidateName, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(txtValidateName, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(txtValidate2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(txtValidate3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(12, 12, 12)
                .addComponent(txtValidate5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtValidate4)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin và tìm kiem", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel8.setText("Tim kiem theo: ");

        cbbSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ten", "Dia Chi", "So dien thoai" }));

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        tbQuanLyKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbQuanLyKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbQuanLyKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbQuanLyKhachHang);

        btNext.setText(">");
        btNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNextActionPerformed(evt);
            }
        });

        btBack.setText("<");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        btBackFirst.setText("||<");
        btBackFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackFirstActionPerformed(evt);
            }
        });

        btBackEnd.setText(">||");
        btBackEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackEndActionPerformed(evt);
            }
        });

        lbls.setText("jLabel9");

        jLabel9.setText("Trang: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbls, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(btBackFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBackEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSearch))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btNext)
                        .addComponent(btBack)
                        .addComponent(btBackFirst)
                        .addComponent(btBackEnd))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbls)
                        .addComponent(jLabel9)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jButton2.setText("Quay lai");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Import Excel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btAdd)
                                    .addGap(49, 49, 49)
                                    .addComponent(btEdit)
                                    .addGap(37, 37, 37)
                                    .addComponent(jButton3)
                                    .addGap(29, 29, 29)
                                    .addComponent(jButton1))
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(80, 80, 80))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAdd)
                            .addComponent(btEdit)
                            .addComponent(jButton1)
                            .addComponent(jButton3))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private int kk() {
        int n = rowOffset += 5;
        return n;
    }

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
        KhachHang kh = new KhachHang();
        Boolean conf1 = false;
        Boolean conf2 = false;
        Boolean conf3 = false;
        Boolean conf4 = false;
        Boolean conf5 = false;
        if (txtTen.getText().isEmpty()) {
            txtValidateName.setText("Khong duoc bo trong ten");
            txtValidateName.setForeground(Color.red);
            txtTen.setBackground(Color.red);
        } else if (!txtTen.getText().matches("^[A-Z a-zÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚÝàáâãèéêìíòóôõùúýĂăĐđĨĩŨũƠơƯưẠ-ỹ]{1,150}+$")) {
            txtValidateName.setText("Tên không duoc chua so hoac cac ky tu dac biet");
            txtValidateName.setForeground(Color.red);
            txtTen.setBackground(Color.red);
        } else {
            txtValidateName.setText("OK");
            txtValidateName.setForeground(Color.GREEN);
            txtTen.setBackground(Color.GREEN);
            kh.setTen(txtTen.getText());
            conf1 = true;
        }
        if (txtDiaChi.getText().isEmpty()) {
            txtValidate4.setText("Khong duoc bo trong Dia chi");
            txtValidate4.setForeground(Color.red);
            txtDiaChi.setBackground(Color.RED);
        } else {
            txtValidate4.setText("OK");
            txtValidate4.setForeground(Color.GREEN);
            kh.setDiaChi(txtDiaChi.getText());
            txtDiaChi.setBackground(Color.GREEN);
            conf2 = true;
        }
        String validateEmail = txtEmail.getText();
        if (txtEmail.getText().isEmpty()) {
            txtValidate5.setText("Khong duoc bo trong email");
            txtValidate5.setForeground(Color.red);
            txtEmail.setBackground(Color.RED);
        } else if (!validateEmail.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            txtValidate5.setText("Sai dinh dang email (example@gmail.com)");
            txtValidate5.setForeground(Color.red);
            txtEmail.setBackground(Color.RED);
        } else {
            txtValidate5.setText("OK");
            txtValidate5.setForeground(Color.GREEN);
            kh.setEmail(txtEmail.getText());
            txtEmail.setBackground(Color.GREEN);
            conf3 = true;
        }
        String validateNgay = txtNgaySinh.getText();
        if (txtNgaySinh.getText().isEmpty()) {
            txtValidate2.setText("Khong duoc bo trong ngay sinh");
            txtValidate2.setForeground(Color.red);
            txtNgaySinh.setBackground(Color.RED);
        } else if (!validateNgay.matches("^\\d{4}\\-(0?[1-9]|1[012])\\-(0?[1-9]|[12][0-9]|3[01])$")) {
            txtValidate2.setText("Sai dinh dang ngay(Nam-Thang-Ngay)");
            txtValidate2.setForeground(Color.red);
            txtNgaySinh.setBackground(Color.RED);
        } else {
            txtValidate2.setText("OK");
            txtValidate2.setForeground(Color.GREEN);
            String ngaySinhs = txtNgaySinh.getText();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            LocalDate localDate = LocalDate.parse(ngaySinhs, formatter);
            java.sql.Date ngaySinh = java.sql.Date.valueOf(localDate);
            kh.setNgaySinh(ngaySinh);
            txtNgaySinh.setBackground(Color.GREEN);
            conf4 = true;

        }
        String vadidateSDT = txtSDT.getText();
        if (txtSDT.getText().isEmpty()) {
            txtValidate3.setText("Khong duoc bo trong So dien thoai");
            txtValidate3.setForeground(Color.red);
            txtSDT.setBackground(Color.RED);
        } else if (!vadidateSDT.matches("(84|0[3|5|7|8|9])+([0-9]{8})\\b")) {
            txtValidate3.setText("Sai dinh dang so dien thoai");
            txtValidate3.setForeground(Color.red);
            txtSDT.setBackground(Color.RED);
        } else {
            txtValidate3.setText("OK");
            txtValidate3.setForeground(Color.GREEN);
            kh.setSdt(txtSDT.getText());
            txtSDT.setBackground(Color.GREEN);
            conf5 = true;
        }

        if (conf1 == true && conf2 == true && conf3 == true && conf4 == true && conf5 == true) {
            JOptionPane.showMessageDialog(rootPane, service.addKhachHang(kh));
            listKhachHangView = service.getAllKhachHang(rowOffset);
            service.showDataTable(dtm, listKhachHangView);
        }

    }//GEN-LAST:event_btAddActionPerformed


    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        // TODO add your handling code here:
        KhachHang kh = new KhachHang();
        String ID = id.getText();
        kh.setTen(txtTen.getText());
        kh.setDiaChi(txtDiaChi.getText());
        kh.setEmail(txtEmail.getText());
        String ngaySinhs = txtNgaySinh.getText();
        java.sql.Date date = java.sql.Date.valueOf(ngaySinhs);
        kh.setNgaySinh((date));
        kh.setSdt(txtSDT.getText());
        JOptionPane.showMessageDialog(rootPane, service.editKhachHang(kh, ID));
        listKhachHangView = service.getAllKhachHang(rowOffset);
        service.showDataTable(dtm, listKhachHangView);
    }//GEN-LAST:event_btEditActionPerformed

    private void tbQuanLyKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbQuanLyKhachHangMouseClicked
        // TODO add your handling code here:
        if (txtSearch.getText().isBlank()) {
            int row = tbQuanLyKhachHang.getSelectedRow();
            fillData(row);
        } else {
            int row = tbQuanLyKhachHang.getSelectedRow();
            fillDataSearch(row);
        }
    }//GEN-LAST:event_tbQuanLyKhachHangMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        if (cbbSearch.getSelectedIndex() == 0) {
            name = txtSearch.getText();
            listSearchTen = service.searchKhachHang(name, rowOffset);
            listSearch = service.searchKhachHang(name, rowOffset);
            for (KhachHangViewModel khachHangViewModel : listSearchTen) {
                System.out.println(khachHangViewModel.toString());

            }
            try {
                service.showDataTable(dtm, listSearchTen);
            } catch (Exception e) {
                service.showDataTable(dtm, listSearchTen);
            }

        }
        if (cbbSearch.getSelectedIndex() == 1) {
            name = txtSearch.getText();
            listSearchDiaChi = service.searchKhachHangDiaChi(name, rowOffset);
            listSearch = service.searchKhachHangDiaChi(name, rowOffset);
            for (KhachHangViewModel khachHangViewModel : listSearchDiaChi) {
                System.out.println(khachHangViewModel.toString());

            }
            try {
                service.showDataTable(dtm, listSearchDiaChi);
            } catch (Exception e) {
                service.showDataTable(dtm, listSearchDiaChi);
            }
        }

        if (cbbSearch.getSelectedIndex() == 2) {
            name = txtSearch.getText();
            listSearchSDT = service.searchKhachHangSDT(name, rowOffset);
            listSearch = service.searchKhachHangSDT(name, rowOffset);
            for (KhachHangViewModel khachHangViewModel : listSearchSDT) {
                System.out.println(khachHangViewModel.toString());

            }
            try {
                service.showDataTable(dtm, listSearchSDT);
            } catch (Exception e) {
                service.showDataTable(dtm, listSearchSDT);
            }
        }

        if (txtSearch.getText().isEmpty()) {
            listKhachHangView = service.getAllKhachHang(rowOffset);
            service.showDataTable(dtm, listKhachHangView);
            int o = listKhachHang.size() % fetch;
            int index = 0;
            loadSoTrang();
        }
//        int o = listSearch.size() % fetch;
//        int index = 0;
//        lbls.setText((index + 1) + "/" + (o + 1) + "");
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        id.setText("");
        txtDiaChi.setText("");
        txtEmail.setText("");
        txtNgaySinh.setText("");
        txtSDT.setText("");
        txtTen.setText("");
        txtValidate2.setText("");
        txtValidate3.setText("");
        txtValidate4.setText("");
        txtValidate5.setText("");
        txtValidateName.setText("");
        txtDiaChi.setBackground(Color.white);
        txtEmail.setBackground(Color.white);
        txtNgaySinh.setBackground(Color.white);
        txtSDT.setBackground(Color.white);
        txtTen.setBackground(Color.white);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenKeyReleased
        // TODO add your handling code here:
        txtTen.setBackground(Color.white);
        txtValidateName.setText("");
    }//GEN-LAST:event_txtTenKeyReleased

    private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySinhActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNgaySinhActionPerformed

    private void txtNgaySinhKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNgaySinhKeyPressed
        // TODO add your handling code here:
        txtNgaySinh.setBackground(Color.white);
        txtValidate2.setText("");
    }//GEN-LAST:event_txtNgaySinhKeyPressed

    private void txtSDTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTKeyReleased
        // TODO add your handling code here:
        String vadidateSDT = txtSDT.getText();
        if (!vadidateSDT.matches("(84|0[3|5|7|8|9])+([0-9]{8})\\b")) {
            txtValidate3.setText("Sai dinh dang so dien thoai");
            txtValidate3.setForeground(Color.red);
            txtSDT.setBackground(Color.RED);
        } else {
            txtValidate3.setText("OK");
            txtValidate3.setForeground(Color.GREEN);
            txtSDT.setBackground(Color.GREEN);

        }


    }//GEN-LAST:event_txtSDTKeyReleased

    private void txtDiaChiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaChiKeyReleased
        // TODO add your handling code here:
        txtDiaChi.setBackground(Color.white);
        txtValidate4.setText("");
    }//GEN-LAST:event_txtDiaChiKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
        String validateEmail = txtEmail.getText();
        if (!validateEmail.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            txtValidate5.setText("Sai dinh dang email (example@gmail.com)");
            txtValidate5.setForeground(Color.red);
            txtEmail.setBackground(Color.RED);
        } else {
            txtValidate5.setText("OK");
            txtValidate5.setForeground(Color.GREEN);
            txtEmail.setBackground(Color.GREEN);
        }
    }//GEN-LAST:event_txtEmailKeyReleased
    int st = 0;
    int end = 5;
    private void btNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNextActionPerformed
        // TODO add your handling code here:

        if (txtSearch.getText().isEmpty()) {
            index++;
            rowOffset += 5;
            if (rowOffset > service.getAllKhachHang1().size() - 1) {
                rowOffset = 0;
                index = 0;
            }
            listKhachHangView = service.getAllKhachHang(rowOffset);
            service.showDataTable(dtm, listKhachHangView);
            loadSoTrang();
        } else {

            if (cbbSearch.getSelectedIndex() == 0) {
                index++;
                rowOffset += 5;
                if (rowOffset > listSearchTen.size()) {
                    rowOffset = 0;
                    index = 0;

                }

                service.showDataTable(dtm, service.searchKhachHang(name, rowOffset));
                loadSoTrang();
            } else {
                index++;
                rowOffset += 5;

                if (rowOffset > listSearchDiaChi.size()) {
                    rowOffset = 0;
                    index = 0;

                }

                service.showDataTable(dtm, service.searchKhachHangDiaChi(name, rowOffset));
                loadSoTrang();
            }
        }
    }//GEN-LAST:event_btNextActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
//        index = ;

        if (txtSearch.getText().isEmpty()) {
            index--;
            rowOffset -= 5;
            if (rowOffset < 0) {
                int c = service.getAllKhachHang1().size() % fetch;
                rowOffset = service.getAllKhachHang1().size() - c;
                index = o;
            }
            listKhachHangView = service.getAllKhachHang(rowOffset);
            service.showDataTable(dtm, listKhachHangView);
            loadSoTrang();
        } else {

            if (cbbSearch.getSelectedIndex() == 0) {
                index--;
                rowOffset -= 5;
                if (rowOffset < 0) {
                    int c = listSearch.size() % fetch;
                    rowOffset = listSearch.size() - c;
                    index = o;

                }

                service.showDataTable(dtm, service.searchKhachHang(name, rowOffset));
                loadSoTrang();
            } else {
                index--;
                rowOffset -= 5;

                if (rowOffset < 0) {
                    int c = listSearch.size() % fetch;
                    rowOffset = listSearch.size() - c;
                    index = o;

                }

                service.showDataTable(dtm, service.searchKhachHangDiaChi(name, rowOffset));
                loadSoTrang();
            }
        }
//        index--;        // TODO add your handling code here:
//        rowOffset -= 5;
//        if (rowOffset < 0) {
//            int c = service.getAllKhachHang1().size() % fetch;
//            rowOffset = service.getAllKhachHang1().size() - c;
//            index = o;
//        }
//        listKhachHangView = service.getAllKhachHang(rowOffset);
//        service.showDataTable(dtm, listKhachHangView);
//        loadSoTrang();
    }//GEN-LAST:event_btBackActionPerformed

    private void btBackFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackFirstActionPerformed

        if (txtSearch.getText().isEmpty() || txtSearch.getText().isBlank()) {
            index = 0;        // TODO add your handling code here:
            int c = service.getAllKhachHang1().size() % fetch;
            rowOffset = 0;
            listKhachHangView = service.getAllKhachHang(rowOffset);
            service.showDataTable(dtm, listKhachHangView);
            loadSoTrang();
        } else {
            if (cbbSearch.getSelectedIndex() == 0) {
                index = 0;        // TODO add your handling code here:
                rowOffset = 0;
                listSearchTen = service.searchKhachHang(name, rowOffset);
                service.showDataTable(dtm, listSearchTen);
                loadSoTrang();
            } else {
                index = 0;        // TODO add your handling code here:
                rowOffset = 0;
                listSearchDiaChi = service.searchKhachHangDiaChi(name, rowOffset);
                service.showDataTable(dtm, listSearchDiaChi);
                loadSoTrang();
            }
        }


    }//GEN-LAST:event_btBackFirstActionPerformed

    private void btBackEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackEndActionPerformed

        if (txtSearch.getText().isEmpty() || txtSearch.getText().isBlank()) {
            index = o;        // TODO add your handling code here:
            int c = service.getAllKhachHang1().size() % fetch;
            rowOffset = service.getAllKhachHang1().size() - c;
            listKhachHangView = service.getAllKhachHang(rowOffset);
            service.showDataTable(dtm, listKhachHangView);
            loadSoTrang();
        } else {
            if (cbbSearch.getSelectedIndex() == 0) {
                // TODO add your handling code here:
                int c = listSearchTen.size() / fetch;
                index = listSearchTen.size() / fetch;
                rowOffset = service.searchKhachHang(name, rowOffset).size() - c;
                listSearchTen = service.searchKhachHang(name, rowOffset);
                service.showDataTable(dtm, listSearchTen);
                loadSoTrang();

            } else {
                // TODO add your handling code here:
                int c = listSearchDiaChi.size() / fetch;
                index = c;
                rowOffset = service.searchKhachHangDiaChi(name, rowOffset).size() - c;
                listSearchDiaChi = service.searchKhachHangDiaChi(name, rowOffset);
                service.showDataTable(dtm, listSearchDiaChi);
                loadSoTrang();
            }
        }

    }//GEN-LAST:event_btBackEndActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ImportExcelKhachHangView iekhv = new ImportExcelKhachHangView();
        iekhv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void fillData(int index) {
        KhachHangViewModel kh = listKhachHangView.get(index);
        id.setText(kh.getId());
        txtDiaChi.setText(kh.getDiaChi());
        txtEmail.setText(kh.getEmail());

        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String strDate = dateFormat.format(kh.getNgaySinh());
        txtNgaySinh.setText(strDate);
        txtSDT.setText(kh.getSdt());
        txtTen.setText(kh.getTen());
    }

    public void fillDataSearch(int index) {
        KhachHangViewModel kh = listSearchDiaChi.get(index);
        id.setText(kh.getId());
        txtDiaChi.setText(kh.getDiaChi());
        txtEmail.setText(kh.getEmail());

        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String strDate = dateFormat.format(kh.getNgaySinh());
        txtNgaySinh.setText(strDate);
        txtSDT.setText(kh.getSdt());
        txtTen.setText(kh.getTen());
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachHangViewQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachHangViewQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachHangViewQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachHangViewQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhachHangViewQuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btBack;
    private javax.swing.JButton btBackEnd;
    private javax.swing.JButton btBackFirst;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btNext;
    private javax.swing.ButtonGroup btgGender;
    private javax.swing.JComboBox<String> cbbSearch;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbls;
    private javax.swing.JTable tbQuanLyKhachHang;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTen;
    private javax.swing.JLabel txtValidate2;
    private javax.swing.JLabel txtValidate3;
    private javax.swing.JLabel txtValidate4;
    private javax.swing.JLabel txtValidate5;
    private javax.swing.JLabel txtValidateName;
    // End of variables declaration//GEN-END:variables
}
