package View;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import DomainModel.NhanVien;
import Service.LoginService;
import Service.ServiceImpl.LoginImpl;
import ViewModel.MaNVViewModel;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author buiti
 */
public class LOGINview extends javax.swing.JFrame {

    /**
     * Creates new form LOGINview
     */
    LoginService impl = new LoginImpl();

    public LOGINview() {
        initComponents();
        auto();
        txtID.setBackground(new java.awt.Color(0, 0, 1, 0));
        txtPass.setBackground(new java.awt.Color(0, 0, 1, 0));
        txtGach1.setBackground(new java.awt.Color(0, 0, 1, 0));
        txtgach2.setBackground(new java.awt.Color(0, 0, 1, 0));

    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnDangKy = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtdis = new javax.swing.JLabel();
        txtShow = new javax.swing.JLabel();
        txtGach1 = new javax.swing.JTextField();
        txtgach2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtRPID1 = new javax.swing.JLabel();
        txtRPPAss = new javax.swing.JLabel();
        checkRm = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BEEPHONE");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 440, 150));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BEEPHONE");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 430, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 510));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/error.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 0, 46, 38));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 410, 39));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Don't have an account ?");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 170, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Username");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        btnDangKy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDangKy.setForeground(new java.awt.Color(255, 255, 255));
        btnDangKy.setText("Sign Up");
        btnDangKy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDangKyMouseClicked(evt);
            }
        });
        jPanel2.add(btnDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));

        txtID.setBackground(new java.awt.Color(51, 51, 51));
        txtID.setFont(txtID.getFont());
        txtID.setForeground(new java.awt.Color(255, 255, 255));
        txtID.setBorder(null);
        jPanel2.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 230, 30));

        txtPass.setFont(txtPass.getFont());
        txtPass.setForeground(new java.awt.Color(255, 255, 255));
        txtPass.setBorder(null);
        txtPass.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 230, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("LOGIN");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 260, 40));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/use.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 40, 30));

        txtdis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtdis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eye_hide.png"))); // NOI18N
        txtdis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtdis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdisMouseClicked(evt);
            }
        });
        jPanel2.add(txtdis, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 40, 30));

        txtShow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eye.png"))); // NOI18N
        txtShow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtShowMouseClicked(evt);
            }
        });
        jPanel2.add(txtShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 40, 30));

        txtGach1.setEditable(false);
        txtGach1.setForeground(new java.awt.Color(255, 255, 255));
        txtGach1.setText("__________________________________________");
        txtGach1.setBorder(null);
        txtGach1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGach1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtGach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 230, -1));

        txtgach2.setEditable(false);
        txtgach2.setForeground(new java.awt.Color(255, 255, 255));
        txtgach2.setText("__________________________________________");
        txtgach2.setBorder(null);
        txtgach2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgach2ActionPerformed(evt);
            }
        });
        jPanel2.add(txtgach2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 230, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Hello ! Let's get started");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 410, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Password");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Or Login With");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 80, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/z3946860666735_30f52c7f5e3d1a6b5fd11409bdce2492.jpg"))); // NOI18N
        jLabel18.setText("QR Căn cước");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 130, 34));
        jPanel2.add(txtRPID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 230, 20));
        jPanel2.add(txtRPPAss, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 230, 20));

        checkRm.setForeground(new java.awt.Color(255, 255, 255));
        checkRm.setText("Remember ?");
        checkRm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRmActionPerformed(evt);
            }
        });
        jPanel2.add(checkRm, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Forgot password");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 100, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loginxam.jpg"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 510));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 410, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtgach2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgach2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgach2ActionPerformed

    private void txtGach1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGach1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGach1ActionPerformed

    private void txtdisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdisMouseClicked
        txtPass.setEchoChar((char) 0);
        txtdis.setVisible(false);
        txtdis.setEnabled(false);
        txtShow.setEnabled(true);
        txtShow.setEnabled(true);
    }//GEN-LAST:event_txtdisMouseClicked

    private void txtShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtShowMouseClicked
        txtPass.setEchoChar((char) 8226);
        txtdis.setVisible(true);
        txtdis.setEnabled(true);
        txtShow.setEnabled(false);
        txtShow.setEnabled(false);

    }//GEN-LAST:event_txtShowMouseClicked

    private void btnDangKyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangKyMouseClicked
        DangKy bhv = new DangKy();
        this.dispose();
        bhv.setVisible(true);
    }//GEN-LAST:event_btnDangKyMouseClicked
    private void auto() {
        txtID.setText(impl.auto().getId());
        txtPass.setText(impl.auto().getPass());
    }
    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        NhanVien nv = new NhanVien();
        String userID = txtID.getText();
        String userPass = txtPass.getText();
        String thongBao = impl.login(userID, userPass);
        Boolean conf1 = false;
        Boolean conf2 = false;
        if (txtID.getText().isEmpty()) {
            txtRPID1.setText("Đang trống");

            txtRPID1.setForeground(Color.white);

        } else {
            conf1 = true;
        }
        if (txtPass.getText().isEmpty()) {
            txtRPPAss.setText("Đang trống");
            txtRPPAss.setForeground(Color.white);
        } else {
            conf2 = true;
        }
        if (conf2 == true && conf1 == true) {
            System.out.println(thongBao);
            if (thongBao.contains("NOT")) {
                JOptionPane.showMessageDialog(this, "tai khoan hoac mat khau khong dung");
            } else {
                if (checkRm.isSelected()) {
                    impl.RememberName(userID, userPass);
                }
                if (thongBao.contains("NV")) {
//                TrangChuNhanVienView nvv = new TrangChuNhanVienView(this, true);
                    
                    TrangChuNhanVienView nvv = new TrangChuNhanVienView();
                    nvv.setVisible(true);
                }
                if (thongBao.contains("QL")) {
                                       
                    TrangChuQuanLyView ql = new TrangChuQuanLyView(txtID.getText());
                    ql.setVisible(true);
                }
                this.dispose();
            }
        }
        
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        String cmnd = "";
//        int camera = cbbWebCam.getSelectedIndex();
        ScanCode sc = new ScanCode(new java.awt.Frame(), true, 0);
        sc.setVisible(true);
        cmnd = sc.getScanResutlx().substring(0, 12);
        System.out.println(cmnd);
        String thongBao = impl.loginWebCam(cmnd);
        List<MaNVViewModel> lisMa = new ArrayList<>();
        System.out.println(lisMa);
        String ma = impl.getMaNV(cmnd).get(0).getMaNV();
       
        MaNVViewModel nv = new MaNVViewModel();
//        String ma = nv.getMaNV();
        if (thongBao.contains("NOT")) {
            JOptionPane.showMessageDialog(this, "sai");
        } else {
            if (thongBao.contains("NV")) {
                TrangChuNhanVienView nvv = new TrangChuNhanVienView();
                nvv.setVisible(true);
            }
            if (thongBao.contains("QL")) {
                TrangChuQuanLyView ql = new TrangChuQuanLyView(ma);
                ql.setVisible(true);
            }
            this.dispose();
        }
    }//GEN-LAST:event_jLabel18MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i < 1.0; i = i + 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(50);
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void checkRmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRmActionPerformed
     
    }//GEN-LAST:event_checkRmActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
       new ForgotPassword().setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGINview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGINview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGINview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGINview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGINview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDangKy;
    private javax.swing.JCheckBox checkRm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtGach1;
    private javax.swing.JTextField txtID;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JLabel txtRPID1;
    private javax.swing.JLabel txtRPPAss;
    private javax.swing.JLabel txtShow;
    private javax.swing.JLabel txtdis;
    private javax.swing.JTextField txtgach2;
    // End of variables declaration//GEN-END:variables
}
