/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DomainModel.KhachHang;
import Service.Email;
import Service.KhachHangService;
import Service.KhuyenMaiService;
import Service.ServiceImpl.EmailimplGiang;
import Service.ServiceImpl.KhachHangServiceImpl;
import Service.ServiceImpl.KhuyenMaiServiceimpl;
import ViewModel.KhachHangViewModel;
import ViewModel.KhuyenMaiViewModel;
import java.io.File;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author togia
 */
public class ViewKhuyenMai extends javax.swing.JFrame {

    private DefaultTableModel dtm = new DefaultTableModel();
    private DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
    private List<KhuyenMaiViewModel> list = new ArrayList<>();
    private List<String> listcombobox = new ArrayList<>();
    private KhuyenMaiService service = new KhuyenMaiServiceimpl();
    private List<KhachHangViewModel> listKH = new ArrayList<>();
    private KhachHangServiceImpl service1 = new KhachHangServiceImpl();
    private EmailimplGiang email = new EmailimplGiang();
    private File file = new File("");

    int rowOffset = 0;
    int fetch = 5;
    String name = "";
    int index = 0;
    int o = 0;

    /**
     * Creates new form ViewKhuyenMai
     */
    public ViewKhuyenMai() {
        initComponents();
        jTable1.setModel(dtm);
        cbbTrangThai.setModel(dcbm);
        String[] hears = {"id", "Mã KM", "Ngày bắt đầu", "Ngày kết thúc", "Giá giảm", "Đơn vị", "Mô tả", "Trạng thái"};
        dtm.setColumnIdentifiers(hears);
        listcombobox.add("Sắp diễn ra");
        listcombobox.add("Đang diễn ra");
        listcombobox.add("Kết thúc");
        dcbm.addAll(listcombobox);
        dcbm.setSelectedItem("Sắp diễn ra");
        service.upDateTrangThai();
        service.getAll(list);
        listKH = service1.getAllKhachHang1();
        list = service.getAllDem(rowOffset);
        System.out.println(rowOffset);
        o = service.getAllDem(rowOffset).size() / fetch;

        loadSoTrang();

    }

    private void loadSoTrang() {
        lbLoadTrang.setText(index + 1 + "");
    }

    private int kk() {
        int n = rowOffset += 5;
        return n;
    }

    public void showdataTable(List<KhuyenMaiViewModel> list) {
        dtm.setRowCount(0);
        for (KhuyenMaiViewModel km : list) {
            dtm.addRow(km.toDataRow());
        }
    }

    public void fillData(int index) {
        KhuyenMaiViewModel km = list.get(index);
        lbID.setText(km.getId());
        txtNgayKT.setText(String.valueOf(km.getNgayBatDau()));
        txtNgayBD.setText(String.valueOf(km.getNgayKetThuc()));
        txtMaKM.setText(km.getMa());
        txtMoTa.setText(km.getMoTa());
        txtGiaGiam.setText(String.valueOf(km.getGiaGiam()));
        cbbTrangThai.setSelectedItem(list.get(index).layTrangThai());
        if (km.isDonVi() == true) {
            radioTruTien.setSelected(true);
        } else {
            radioPhanTram.setSelected(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMaKM = new javax.swing.JTextField();
        radioPhanTram = new javax.swing.JRadioButton();
        btAdd = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cbbTrangThai = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();
        btExit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtMoTa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNgayBD = new javax.swing.JTextField();
        btSort = new javax.swing.JButton();
        txtNgayKT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtGiaGiam = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        radioTruTien = new javax.swing.JRadioButton();
        btSend = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btTatCa = new javax.swing.JButton();
        btDangDienRa = new javax.swing.JButton();
        btSapDienRa = new javax.swing.JButton();
        btDaKT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnext = new javax.swing.JButton();
        btSau = new javax.swing.JButton();
        lbLoadTrang = new javax.swing.JLabel();
        btNextt = new javax.swing.JButton();
        btSauu = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Mã Khuyến mại");

        buttonGroup1.add(radioPhanTram);
        radioPhanTram.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioPhanTram.setText(" %");

        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btEdit.setText("Edit");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        btClear.setText("New");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });

        jLabel12.setText("Trạng thái");

        cbbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("ID");

        btExit.setText("Exit");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        jLabel4.setText("Mô tả");

        jLabel5.setText("Ngày bắt đầu");

        jLabel6.setText("Ngày kết thúc");

        btSort.setText("Sort");
        btSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSortActionPerformed(evt);
            }
        });

        jLabel7.setText("Giá giảm");

        jLabel8.setText("Đơn vị");

        radioTruTien.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radioTruTien);
        radioTruTien.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        radioTruTien.setText("Money");

        btSend.setText("Send Email");
        btSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSend)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btAdd)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbID, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtNgayKT)
                                            .addComponent(txtNgayBD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtGiaGiam))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(radioTruTien, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(radioPhanTram, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(63, 63, 63))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(btEdit)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btDelete)
                                    .addGap(28, 28, 28)
                                    .addComponent(btExit)
                                    .addGap(23, 23, 23)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btSort)
                                .addGap(58, 58, 58)
                                .addComponent(btClear)
                                .addGap(136, 136, 136))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(lbID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtGiaGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(radioTruTien)
                    .addComponent(radioPhanTram))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdd)
                    .addComponent(btEdit)
                    .addComponent(btDelete)
                    .addComponent(btExit))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btClear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSort, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSend))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Danh sách mã khuyến mại");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel2.setText("Tạo mã giảm giá toàn Shop hoặc mã giảm giá sản phẩm ngay bây giờ để thu hút người mua ");

        btTatCa.setBackground(new java.awt.Color(255, 204, 0));
        btTatCa.setText("Tất cả");
        btTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTatCaActionPerformed(evt);
            }
        });

        btDangDienRa.setBackground(new java.awt.Color(255, 204, 102));
        btDangDienRa.setText("Đang diễn ra");
        btDangDienRa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDangDienRaActionPerformed(evt);
            }
        });

        btSapDienRa.setBackground(new java.awt.Color(255, 255, 0));
        btSapDienRa.setText("Sắp diễn ra");
        btSapDienRa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSapDienRaActionPerformed(evt);
            }
        });

        btDaKT.setBackground(new java.awt.Color(255, 255, 153));
        btDaKT.setText("Đã kết thúc");
        btDaKT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDaKTActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel10.setText("Search");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnext.setText(">>");
        btnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnextActionPerformed(evt);
            }
        });

        btSau.setText("<<");
        btSau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSauActionPerformed(evt);
            }
        });

        btNextt.setText(">|");
        btNextt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNexttActionPerformed(evt);
            }
        });

        btSauu.setText("|<");
        btSauu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSauuActionPerformed(evt);
            }
        });

        jLabel11.setText("Trang  : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btTatCa)
                                .addGap(30, 30, 30)
                                .addComponent(btSapDienRa)
                                .addGap(42, 42, 42)
                                .addComponent(btDangDienRa)
                                .addGap(42, 42, 42)
                                .addComponent(btDaKT))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbLoadTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(btSauu)
                        .addGap(18, 18, 18)
                        .addComponent(btSau)
                        .addGap(79, 79, 79)
                        .addComponent(btnext)
                        .addGap(18, 18, 18)
                        .addComponent(btNextt)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTatCa)
                    .addComponent(btDangDienRa)
                    .addComponent(btSapDienRa)
                    .addComponent(btDaKT))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btNextt)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btSau)
                                .addComponent(btSauu)
                                .addComponent(btnext)))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbLoadTrang)
                            .addComponent(jLabel11))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        KhuyenMaiViewModel kh = new KhuyenMaiViewModel();
        String ma = txtMaKM.getText();
        String moTa = txtMoTa.getText();
        boolean donVi = radioTruTien.isSelected();
        Double giaGiam = Double.valueOf(txtGiaGiam.getText());
        String ngayBD = txtNgayBD.getText();
        DateTimeFormatter formatter1 = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate localDate1 = LocalDate.parse(ngayBD, formatter1);
        java.sql.Date ngayBDs = java.sql.Date.valueOf(localDate1);
        kh.setNgayBatDau(ngayBDs);
        String ngayKT = txtNgayKT.getText();
        DateTimeFormatter formatter2 = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate localDate2 = LocalDate.parse(ngayKT, formatter2);
        java.sql.Date ngayKTs = java.sql.Date.valueOf(localDate2);
        kh.setNgayKetThuc(ngayKTs);
        KhuyenMaiViewModel km = new KhuyenMaiViewModel(ma, ngayBDs, ngayKTs, giaGiam, donVi, moTa);
        JOptionPane.showMessageDialog(rootPane, service.add(km));
        list.removeAll(list);
        service.upDateTrangThai();
        for (int i = 0; i < listKH.size(); i++) {
            email.sendEmail1(listKH.get(index).getEmail(), "Đã thêm mã KM mới","Mời bạn đến cửa hàng để nhận được nhiều ưu đãi");  
        }
      // for (KhachHangViewModel khachHangViewModel : listKH) {
        //   email.sendEmail1(khachHangViewModel.getEmail(), "Đã thêm mã KM mới","Mời bạn đến cửa hàng để nhận được nhiều ưu đãi");                
      //  }
        service.getAll(list);
        showdataTable(list);
    }//GEN-LAST:event_btAddActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed

        KhuyenMaiViewModel km = new KhuyenMaiViewModel();
        String id = lbID.getText();
        km.setMa(txtMaKM.getText());
        km.setMoTa(txtMoTa.getText());
        boolean donVi = radioTruTien.isSelected();
        Double giaGiam = Double.valueOf(txtGiaGiam.getText());
        km.setGiaGiam(giaGiam);
        km.setDonVi(donVi);
        int trangThai = 0;
        if (cbbTrangThai.getSelectedItem() == "Đang diễn ra") {
            trangThai = 0;

        } else if (cbbTrangThai.getSelectedItem() == "Sắp diễn ra") {
            trangThai = 1;
        } else {
            trangThai = 2;
        }
        String ngayBD = txtNgayBD.getText();
        DateTimeFormatter formatter1 = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate localDate1 = LocalDate.parse(ngayBD, formatter1);
        java.sql.Date ngayBDs = java.sql.Date.valueOf(localDate1);
        km.setNgayBatDau(ngayBDs);
        String ngayKT = txtNgayKT.getText();
        DateTimeFormatter formatter2 = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate localDate2 = LocalDate.parse(ngayKT, formatter2);
        java.sql.Date ngayKTs = java.sql.Date.valueOf(localDate2);
        km.setNgayKetThuc(ngayKTs);
        JOptionPane.showMessageDialog(rootPane, service.update(id, km));
        list.removeAll(list);
        service.getAll(list);
        showdataTable(list);
    }//GEN-LAST:event_btEditActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        int i = jTable1.getSelectedRow();
        JOptionPane.showMessageDialog(rootPane, service.delete(list.get(i).getId()));
        list.removeAll(list);
        service.getAll(list);
        showdataTable(list);
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        txtGiaGiam.setText("");
        txtMaKM.setText("");
        txtMoTa.setText("");
        txtNgayBD.setText("");
        txtNgayKT.setText("");
    }//GEN-LAST:event_btClearActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btExitActionPerformed

    private void btSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSortActionPerformed
        new KhuyenMaiServiceimpl().sapXep(list);
        showdataTable(list);
    }//GEN-LAST:event_btSortActionPerformed

    private void btTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTatCaActionPerformed
        showdataTable(list);
    }//GEN-LAST:event_btTatCaActionPerformed

    private void btDangDienRaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangDienRaActionPerformed
        List<KhuyenMaiViewModel> listShowDangDienRa = new KhuyenMaiServiceimpl().listShowDangDienRa(list);
        showdataTable(listShowDangDienRa);
    }//GEN-LAST:event_btDangDienRaActionPerformed

    private void btSapDienRaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSapDienRaActionPerformed
        List<KhuyenMaiViewModel> listShowSapDienRa = new KhuyenMaiServiceimpl().listShowSapDienRa(list);
        showdataTable(listShowSapDienRa);
    }//GEN-LAST:event_btSapDienRaActionPerformed

    private void btDaKTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDaKTActionPerformed
        List<KhuyenMaiViewModel> listShowDaKT = new KhuyenMaiServiceimpl().listShowDaKT(list);
        showdataTable(listShowDaKT);
    }//GEN-LAST:event_btDaKTActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        fillData(row);
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        List<KhuyenMaiViewModel> listSearch = service.timTheoMa(service.sget(), txtSearch.getText());
        showdataTable(listSearch);

    }//GEN-LAST:event_txtSearchKeyReleased
    int st = 0;
    int end = 5;
    private void btnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnextActionPerformed
        if (txtSearch.getText().isEmpty()) {
            index++;
            rowOffset += 5;
            if (rowOffset > service.getAllDem(rowOffset).size() - 1) {
                rowOffset = 0;
                index = 0;
            }
            list = service.getAllDem(rowOffset);
            showdataTable(list);
            loadSoTrang();

        }
    }//GEN-LAST:event_btnextActionPerformed

    private void btNexttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNexttActionPerformed
        if (txtSearch.getText().isEmpty() || txtSearch.getText().isBlank()) {
            index = o;        // TODO add your handling code here:
            int c = service.getAllDem(rowOffset).size() % fetch;
            rowOffset = service.getAllDem(rowOffset).size() - c;
            list = service.getAllDem(rowOffset);
            showdataTable(list);
            loadSoTrang();
        }
    }//GEN-LAST:event_btNexttActionPerformed

    private void btSauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSauActionPerformed

        if (txtSearch.getText().isEmpty()) {
            index--;
            rowOffset -= 5;
            if (rowOffset < 0) {
                int c = service.getAllDem(rowOffset).size() % fetch;
                rowOffset = service.getAllDem(rowOffset).size() - c;
                index = o;
            }
            list = service.getAllDem(rowOffset);
            showdataTable(list);
            loadSoTrang();
        }
    }//GEN-LAST:event_btSauActionPerformed

    private void btSauuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSauuActionPerformed
        if (txtSearch.getText().isEmpty() || txtSearch.getText().isBlank()) {
            index = 0;        // TODO add your handling code here:
            int c = service.getAllDem(rowOffset).size() % fetch;
            rowOffset = 0;
            list = service.getAllDem(rowOffset);
            showdataTable(list);
            loadSoTrang();
    }//GEN-LAST:event_btSauuActionPerformed
    }
    private void btSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSendActionPerformed
        ChonEmailView emai = new ChonEmailView(this, rootPaneCheckingEnabled);
        this.dispose();
        emai.setVisible(true);
    }//GEN-LAST:event_btSendActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewKhuyenMai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDaKT;
    private javax.swing.JButton btDangDienRa;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btNextt;
    private javax.swing.JButton btSapDienRa;
    private javax.swing.JButton btSau;
    private javax.swing.JButton btSauu;
    private javax.swing.JButton btSend;
    private javax.swing.JButton btSort;
    private javax.swing.JButton btTatCa;
    private javax.swing.JButton btnext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbLoadTrang;
    private javax.swing.JRadioButton radioPhanTram;
    private javax.swing.JRadioButton radioTruTien;
    private javax.swing.JTextField txtGiaGiam;
    private javax.swing.JTextField txtMaKM;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtNgayBD;
    private javax.swing.JTextField txtNgayKT;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
