/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Service.ServiceImpl.HoaDonImpl;
import ViewModel.VIewModelSanPhamHoaDon;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import ViewModel.ViewModelHoaDon;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class ViewHoaDon extends javax.swing.JFrame {

    private DefaultTableModel tableHoaDon = new DefaultTableModel();
    private DefaultTableModel tableSanPhamHD = new DefaultTableModel();
    private DefaultComboBoxModel ccbTim = new DefaultComboBoxModel();
    private DefaultComboBoxModel ccbSapXep = new DefaultComboBoxModel();
    private List<ViewModelHoaDon> listGetAll = new ArrayList<>();
    private List<ViewModelHoaDon> listSearch = new ArrayList<>();
    private List<ViewModelHoaDon> listSort = new ArrayList<>();
    private List<String> ccbFind = new ArrayList<>();
    private List<VIewModelSanPhamHoaDon> listGetSP = new ArrayList<>();
    private List<String> ccb = new ArrayList<>();
    private HoaDonImpl sv = new HoaDonImpl();
    String name = "";
    int TrangThai = 0;
    String path = "";
    int a;
    int b;
    String srcFile = "";

    public ViewHoaDon() {
        initComponents();
        tlbHoaDon.setModel(tableHoaDon);
        tlbSanPham.setModel(tableSanPhamHD);
        ccbFilter.setModel(ccbSapXep);
        ccb.add("Tất Cả");
        ccb.add("Theo giá từ thấp lên cao");
        ccb.add("Theo giá từ cao xuống thấp");
        ccb.add("Chưa Thanh Toán");
        ccb.add("Đã Thanh Toán");

        for (String string : ccb) {
            ccbSapXep.addElement(string);
        }
        for (String string : ccbFind) {
            ccbTim.addElement(string);
        }

        String[] heaaderHoaDon = {"Mã HD", "Tên NV", "Tên KH", "Ngày Tạo", "Mã Khuyến Mại", "Giá Giảm", "Tổng Tiền", "Trạng Thái", "Tổng số SP"};
        tableHoaDon.setColumnIdentifiers(heaaderHoaDon);
        String[] headerSanPham = {"Mã HD ", "Mã DT", "Tên SP", "Hãng", "Dòng", "Giá Bán", "Độ Mới", "Mô tả"};
        tableSanPhamHD.setColumnIdentifiers(headerSanPham);

        listGetAll = sv.getAll(listGetAll);
        listSearch = sv.getAll(listGetAll);
        sv.showData(listGetAll, tableHoaDon);

        a = sv.getSLHoaDonChuaThanhToan();
        b = sv.getSLHoaDonThanhToan();

        labelHoaDonChuaThanhToan.setText(a + "");
        labelHoaDonDaThanhToan.setText(b + "");

        int TrangThai = 0;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tlbHoaDon = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tlbSanPham = new javax.swing.JTable();
        btnDong = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnXuatHoaDon = new javax.swing.JButton();
        btnGuiEmail = new javax.swing.JButton();
        ccbFilter = new javax.swing.JComboBox<>();
        btnExcel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelHoaDonDaThanhToan = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelHoaDonChuaThanhToan = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setText("Hóa Đơn");

        jLabel2.setText("Tìm Kiếm:");

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        jLabel3.setText("Sắp Xếp Theo:");

        tlbHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã HĐ", "Tên NV", "Tên KH", "Ngày Tạo", "Mã Khuyến Mại", "Tổng Tiền", "Trạng Thái", "Title 8"
            }
        ));
        tlbHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tlbHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tlbHoaDon);

        tlbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã ĐT", "Mã HĐ", "Tên SP", "Hãng", "Dòng", "Giá Bán", "Độ Mới", "Mô Tả"
            }
        ));
        jScrollPane2.setViewportView(tlbSanPham);

        btnDong.setText("Exit");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Danh Sách Hóa Đơn");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Danh Sách Sản Phẩm");

        btnXuatHoaDon.setText("Xuất Hóa Đơn");
        btnXuatHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatHoaDonActionPerformed(evt);
            }
        });

        btnGuiEmail.setText("Gửi Email ");
        btnGuiEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiEmailActionPerformed(evt);
            }
        });

        ccbFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ccbFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccbFilterActionPerformed(evt);
            }
        });

        btnExcel.setText("Xuất Excel");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        labelHoaDonDaThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelHoaDonDaThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        labelHoaDonDaThanhToan.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(labelHoaDonDaThanhToan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(labelHoaDonDaThanhToan)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelHoaDonChuaThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelHoaDonChuaThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        labelHoaDonChuaThanhToan.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(labelHoaDonChuaThanhToan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(labelHoaDonChuaThanhToan)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Số hóa đơn đã thanh toán:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Số hóa đơn chưa thanh toán:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(517, 517, 517))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(50, 50, 50)
                        .addComponent(ccbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(408, 408, 408))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(btnGuiEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(btnXuatHoaDon)
                        .addGap(56, 56, 56)
                        .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(ccbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXuatHoaDon)
                    .addComponent(btnGuiEmail)
                    .addComponent(btnExcel)
                    .addComponent(btnDong))
                .addGap(1, 1, 1)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tlbHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlbHoaDonMouseClicked
        // TODO add your handling code here:
        int row = 0;

        if (ccbFilter.getSelectedIndex() == 0) {
            row = tlbHoaDon.getSelectedRow();
            String mahd = listGetAll.get(row).getMaHD();
            listGetSP = sv.getAllSp(mahd);
            sv.showData1(listGetSP, tableSanPhamHD);

        }
        if (ccbFilter.getSelectedIndex() == 1) {
            row = tlbHoaDon.getSelectedRow();
            String mahd = listSearch.get(row).getMaHD();
            listGetSP = sv.getAllSp(mahd);
            sv.showData1(listGetSP, tableSanPhamHD);

        }
        if (ccbFilter.getSelectedIndex() == 2) {
            row = tlbHoaDon.getSelectedRow();
            String mahd = listSearch.get(row).getMaHD();
            listGetSP = sv.getAllSp(mahd);
            sv.showData1(listGetSP, tableSanPhamHD);

        }
        if (ccbFilter.getSelectedIndex() == 3) {
            row = tlbHoaDon.getSelectedRow();
            String mahd = listSort.get(row).getMaHD();
            listGetSP = sv.getAllSp(mahd);
            sv.showData1(listGetSP, tableSanPhamHD);

        }
        if (ccbFilter.getSelectedIndex() == 4) {
            row = tlbHoaDon.getSelectedRow();
            String mahd = listSort.get(row).getMaHD();
            listGetSP = sv.getAllSp(mahd);
            sv.showData1(listGetSP, tableSanPhamHD);

        }


    }//GEN-LAST:event_tlbHoaDonMouseClicked

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        name = txtTimKiem.getText();
        sv.showData(sv.searchHoaDon(name), tableHoaDon);
        listSearch = sv.searchHoaDon(name);
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //ViewHoaDon view = new ViewHoaDon();
        //view.setVisible(true);
    }//GEN-LAST:event_btnDongActionPerformed

    private void ccbLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void ccbFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccbFilterActionPerformed
        // TODO add your handling code here:
        String text = txtTimKiem.getText();

        if (ccbFilter.getSelectedIndex() == 0) {
            sv.showData(listGetAll, tableHoaDon);
        } else if (!text.isEmpty()) {
            sv.showData(listSearch, tableHoaDon);
        }

        if (ccbFilter.getSelectedIndex() == 1) {
            sv.giaCaoXuongThap(listSearch);
            sv.showData(listSearch, tableHoaDon);
        }
        if (ccbFilter.getSelectedIndex() == 2) {

            sv.giaThapLenCao(listSearch);
            sv.showData(listSearch, tableHoaDon);
            ;
        }
        if (ccbFilter.getSelectedIndex() == 3) {
            listSort.removeAll(listSort);
            for (ViewModelHoaDon viewModelHoaDon : listSearch) {
                if (viewModelHoaDon.getTrangThai() == 0) {
                    listSort.add(viewModelHoaDon);
                }
            }
            sv.showData(listSort, tableHoaDon);
        }

        if (ccbFilter.getSelectedIndex() == 4) {

            listSort.removeAll(listSort);
            for (ViewModelHoaDon viewModelHoaDon : listSearch) {
                if (viewModelHoaDon.getTrangThai() == 1) {
                    listSort.add(viewModelHoaDon);
                }
            }
            sv.showData(listSort, tableHoaDon);
        }
    }//GEN-LAST:event_ccbFilterActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        // TODO add your handling code here:

        String nameFile = JOptionPane.showInputDialog("Đặt tên file: ");
        path = "C:\\Users\\PC\\Documents\\du_an_1JDBC\\source\\" + nameFile + ".xlsx";

        if (nameFile.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Hãy nhập tên cho file!!");
        } else {

            if (ccbFilter.getSelectedIndex() == 0) {
                sv.exportExcel(listGetAll, path);
                JOptionPane.showMessageDialog(this, "Xuất file thành công");
            }
            if (ccbFilter.getSelectedIndex() == 1) {
                sv.exportExcel(listSearch, path);
                JOptionPane.showMessageDialog(this, "Xuất file thành công");
            }
            if (ccbFilter.getSelectedIndex() == 2) {
                sv.exportExcel(listSearch, path);
                JOptionPane.showMessageDialog(this, "Xuất file thành công");
            }
            if (ccbFilter.getSelectedIndex() == 3) {
                sv.exportExcel(listSort, path);
                JOptionPane.showMessageDialog(this, "Xuất file thành công");
            }
            if (ccbFilter.getSelectedIndex() == 4) {
                sv.exportExcel(listSort, path);
                JOptionPane.showMessageDialog(this, "Xuất file thành công");
            }

        }
//        String nameFile = JOptionPane.showInputDialog("Đặt tên file: ");
//        
//        JFileChooser fileChooser = new JFileChooser();
//        fileChooser.setCurrentDirectory(new File("."));
//        int response = fileChooser.showSaveDialog(null);
//        if (response == JFileChooser.APPROVE_OPTION) {
//            File file = new File(fileChooser.getSelectedFile().getAbsolutePath());
//            System.out.println(file);
//            path = file + ".xlsx";
//        }
//        if(ccbFilter.getSelectedIndex() == 0){
//            sv.exportExcel(listGetAll, path);
//        }


    }//GEN-LAST:event_btnExcelActionPerformed

    private void btnXuatHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatHoaDonActionPerformed
        // TODO add your handling code here:
        int row = 0;
        ViewModelHoaDon viewhd;
        String filePath = "";
        int trangthai = 0;

        if (ccbFilter.getSelectedIndex() == 0) {
            row = tlbHoaDon.getSelectedRow();
            trangthai = listGetAll.get(row).getTrangThai();
        } else if (ccbFilter.getSelectedIndex() == 1) {
            row = tlbHoaDon.getSelectedRow();
            trangthai = listSearch.get(row).getTrangThai();
        } else if (ccbFilter.getSelectedIndex() == 2) {
            row = tlbHoaDon.getSelectedRow();
            trangthai = listSearch.get(row).getTrangThai();
        } else if (ccbFilter.getSelectedIndex() == 3) {
            row = tlbHoaDon.getSelectedRow();
            trangthai = listSort.get(row).getTrangThai();
        } else if (ccbFilter.getSelectedIndex() == 4) {
            row = tlbHoaDon.getSelectedRow();
            trangthai = listSort.get(row).getTrangThai();
        }

        if (trangthai != 0) {
            filePath = JOptionPane.showInputDialog("Nhập tên cho file: ");

            if (filePath.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Hay nhap ten cho file!!!");
            } else {
                path = "C:\\Users\\PC\\Documents\\du_an_1JDBC\\source\\" + filePath + ".docx";
                if (ccbFilter.getSelectedIndex() == 0) {
                    row = tlbHoaDon.getSelectedRow();
                    viewhd = listGetAll.get(row);
                    sv.exportWord(viewhd, path);
                    JOptionPane.showMessageDialog(this, "Xuất file thành công");
                } else if (ccbFilter.getSelectedIndex() == 1) {
                    row = tlbHoaDon.getSelectedRow();
                    viewhd = listSearch.get(row);
                    sv.exportWord(viewhd, path);
                    JOptionPane.showMessageDialog(this, "Xuất file thành công");
                } else if (ccbFilter.getSelectedIndex() == 2) {
                    row = tlbHoaDon.getSelectedRow();
                    viewhd = listSearch.get(row);
                    sv.exportWord(viewhd, path);
                    JOptionPane.showMessageDialog(this, "Xuất file thành công");
                } else if (ccbFilter.getSelectedIndex() == 3) {
                    row = tlbHoaDon.getSelectedRow();
                    viewhd = listSort.get(row);
                    sv.exportWord(viewhd, path);
                    JOptionPane.showMessageDialog(this, "Xuất file thành công");
                } else if (ccbFilter.getSelectedIndex() == 4) {
                    row = tlbHoaDon.getSelectedRow();
                    viewhd = listSort.get(row);
                    sv.exportWord(viewhd, path);
                    JOptionPane.showMessageDialog(this, "Xuất file thành công");
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Hóa đơn chưa thanh toán không thể xuất file");
        }
//        tlbHoaDon.getSelectedRow();
//        viewhd = listGetAll.get(row);
//        sv.exportWord(viewhd, path);

    }//GEN-LAST:event_btnXuatHoaDonActionPerformed

    private void btnGuiEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiEmailActionPerformed
        // TODO add your handling code here:
        SendEmailHoaDon view = new SendEmailHoaDon();
        this.dispose();
        view.setVisible(true);

    }//GEN-LAST:event_btnGuiEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnGuiEmail;
    private javax.swing.JButton btnXuatHoaDon;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> ccbFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelHoaDonChuaThanhToan;
    private javax.swing.JLabel labelHoaDonDaThanhToan;
    private javax.swing.JTable tlbHoaDon;
    private javax.swing.JTable tlbSanPham;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
