/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View.SanPham;

import DomainModel.Hang;
import Service.ServiceImpl.TSPImpl;
import Service.ThemSPServices;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author haha
 */
public class HangView extends javax.swing.JDialog {

    private ThemSPServices tsp = new TSPImpl();
    private DefaultTableModel modelTBL;
    private DefaultTableModel modelTBL1;
    private int index = -1;
    private int trangThai = 0;
    private List<Hang> ls = new ArrayList<>();
    private Hang hang = null;

    /**
     * Creates new form CameraView
     */
    public HangView(java.awt.Frame parent, boolean modal, String id) {
        super(parent, modal);
        initComponents();
        modelTBL = (DefaultTableModel) tblHang1.getModel();
        modelTBL1 = (DefaultTableModel) tblHang2.getModel();
        fillTable(tsp.getHang(1), modelTBL);
        ls = tsp.getHang(1);
        fillTable(tsp.getHang(0), modelTBL1);
    }

    private void fillTable(List<Hang> qg, DefaultTableModel md) {
        md.setRowCount(0);
        for (Hang quocGia : qg) {
            Object[] row = new Object[]{quocGia.getMa(), quocGia.getTen()};
            md.addRow(row);
        }

    }

    public Hang returnHang() {

        return hang;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTHang = new javax.swing.JTextField();
        txtMHang = new javax.swing.JTextField();
        cbbHang = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnChon = new javax.swing.JButton();
        btnThem1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHang1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHang2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hãng");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Tên Hãng");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 69, -1));

        jLabel1.setText("Mã Hãng");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtTHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTHangActionPerformed(evt);
            }
        });
        jPanel1.add(txtTHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 25, 171, -1));
        jPanel1.add(txtMHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 54, 173, -1));

        cbbHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Không có", "Đang có" }));
        jPanel1.add(cbbHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 83, 173, -1));

        jLabel3.setText("Trạng thái");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 86, -1, -1));

        btnXoa.setText("Thêm");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 40));

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 130, 110, 40));

        btnChon.setText("Thoát");
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });
        jPanel1.add(btnChon, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 180, 110, 40));

        btnThem1.setText("Xóa");
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, 40));

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        tblHang1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã hãng", "Tên hãng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHang1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblHang1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblHang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHang1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHang1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Đang có", jPanel2);

        tblHang2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã hang", "Tên hang"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHang2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblHang2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblHang2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHang2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHang2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Đã xóa", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTHangActionPerformed

    private void tblHang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHang1MouseClicked

        index = tblHang1.getSelectedRow();
        Hang qg = ls.get(index);
        txtTHang.setText(qg.getTen());
        txtMHang.setText(qg.getMa());
        cbbHang.setSelectedIndex(qg.getTrangThai());
        hang = qg;

    }//GEN-LAST:event_tblHang1MouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        String ten = txtTHang.getText();
        String ma = txtMHang.getText();
        if (ten.isBlank() || ma.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Không được để trống thông tin");
        }
        Hang quocGia = new Hang("", ma, ten, cbbHang.getSelectedIndex());
        JOptionPane.showMessageDialog(rootPane, tsp.themHang(quocGia));
        fillTable(tsp.getHang(1), modelTBL);
        fillTable(tsp.getHang(0), modelTBL1);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblHang2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHang2MouseClicked
        index = tblHang2.getSelectedRow();
        Hang qg = tsp.getHang(0).get(index);
        txtTHang.setText(qg.getTen());
        txtMHang.setText(qg.getMa());
        hang = qg;
        cbbHang.setSelectedIndex(qg.getTrangThai());
    }//GEN-LAST:event_tblHang2MouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if (trangThai == 1) {
            trangThai = 0;
        } else {
            trangThai = 1;
        }

    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        String ten = txtTHang.getText();
        String ma = txtMHang.getText();
        String id = "";
        if (trangThai == 1) {
            id = tsp.getHang(1).get(index).getId();
        } else {
            id = tsp.getHang(0).get(index).getId();
        }
        if (ten.isBlank() || ma.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Không được để trống thông tin");
        }
        Hang quocGia = new Hang(id, ma, ten, cbbHang.getSelectedIndex());
        JOptionPane.showMessageDialog(rootPane, tsp.suaHang(quocGia));
        fillTable(tsp.getHang(1), modelTBL);
        fillTable(tsp.getHang(0), modelTBL1);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnChonActionPerformed

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        String ten = txtTHang.getText();
        String ma = txtMHang.getText();
        String id = "";
        if (trangThai == 1) {
            id = tsp.getHang(1).get(index).getId();
        } else {
            id = tsp.getHang(0).get(index).getId();
        }
        if (ten.isBlank() || ma.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Không được để trống thông tin");
        }
        Hang quocGia = new Hang(id, ma, ten, 0);
        JOptionPane.showMessageDialog(rootPane, tsp.suaHang(quocGia));
        fillTable(tsp.getHang(1), modelTBL);
        fillTable(tsp.getHang(0), modelTBL1);
    }//GEN-LAST:event_btnThem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HangView dialog = new HangView(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChon;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblHang1;
    private javax.swing.JTable tblHang2;
    private javax.swing.JTextField txtMHang;
    private javax.swing.JTextField txtTHang;
    // End of variables declaration//GEN-END:variables
}
