/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View.SanPham;

import DomainModel.QuocGia;
import Service.ServiceImpl.TSPImpl;
import Service.ThemSPServices;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author haha
 */
public class QuocGiaView extends javax.swing.JDialog {

    ThemSPServices tsp = new TSPImpl();
    DefaultTableModel modelTBL;
    DefaultTableModel modelTBL1;
    int index = -1;
    int trangThai = 0;
    List<QuocGia> ls = new ArrayList<>();
    QuocGia quocGia = null;

    /**
     * Creates new form CameraView
     */
    public QuocGiaView(java.awt.Frame parent, boolean modal, String id) {
        super(parent, modal);
        initComponents();
        modelTBL = (DefaultTableModel) tblQuocGia1.getModel();
        modelTBL1 = (DefaultTableModel) tblQuocGia2.getModel();
        fillTable(tsp.getQG(1), modelTBL);
        ls = tsp.getQG(1);
        fillTable(tsp.getQG(0), modelTBL1);
    }

    private void fillTable(List<QuocGia> qg, DefaultTableModel md) {
        md.setRowCount(0);
        for (QuocGia quocGia : qg) {
            Object[] row = new Object[]{quocGia.getMa(), quocGia.getTen()};
            md.addRow(row);
        }

    }

    public QuocGia returnQuocGia() {

        return quocGia;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMaQuocGia = new javax.swing.JTextField();
        txtTenQuocGia = new javax.swing.JTextField();
        cbbQuocGia = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnChon = new javax.swing.JButton();
        btnChon1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQuocGia1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblQuocGia2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quốc gia");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Mã quốc gia");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 57, 69, -1));

        jLabel1.setText("Tên quốc gia");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 28, -1, -1));

        txtMaQuocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaQuocGiaActionPerformed(evt);
            }
        });
        jPanel1.add(txtMaQuocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 25, 171, -1));
        jPanel1.add(txtTenQuocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 54, 173, -1));

        cbbQuocGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Không có", "Đang có" }));
        jPanel1.add(cbbQuocGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 83, 173, -1));

        jLabel3.setText("Trạng thái");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 86, -1, -1));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, 40));

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 76, 40));

        btnChon.setText("Chọn");
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });
        jPanel1.add(btnChon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 75, 40));

        btnChon1.setText("Xóa");
        btnChon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChon1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnChon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 75, 40));

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        tblQuocGia1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã quốc gia", "Tên quốc gia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblQuocGia1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblQuocGia1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblQuocGia1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQuocGia1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQuocGia1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Đang có", jPanel2);

        tblQuocGia2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã quốc gia", "Tên quốc gia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblQuocGia2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblQuocGia2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblQuocGia2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQuocGia2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblQuocGia2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Đã xóa", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaQuocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaQuocGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaQuocGiaActionPerformed

    private void tblQuocGia1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuocGia1MouseClicked

        index = tblQuocGia1.getSelectedRow();
        QuocGia qg = ls.get(index);
        txtMaQuocGia.setText(qg.getTen());
        txtTenQuocGia.setText(qg.getMa());
        cbbQuocGia.setSelectedIndex(qg.getTrangThai());
        quocGia = qg;

    }//GEN-LAST:event_tblQuocGia1MouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String ten = txtMaQuocGia.getText();
        String ma = txtTenQuocGia.getText();
        if (ten.isBlank() || ma.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Không được để trống thông tin");
        }
        QuocGia quocGia = new QuocGia("", ma, ten, cbbQuocGia.getSelectedIndex());
        JOptionPane.showMessageDialog(rootPane, tsp.themQG(quocGia));
        fillTable(tsp.getQG(1), modelTBL);
        fillTable(tsp.getQG(0), modelTBL1);
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblQuocGia2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuocGia2MouseClicked
        index = tblQuocGia2.getSelectedRow();
        QuocGia qg = tsp.getQG(0).get(index);
        txtMaQuocGia.setText(qg.getTen());
        txtTenQuocGia.setText(qg.getMa());
        cbbQuocGia.setSelectedIndex(qg.getTrangThai());
        quocGia = qg;
    }//GEN-LAST:event_tblQuocGia2MouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if (trangThai == 1) {
            trangThai = 0;
        } else {
            trangThai = 1;
        }

    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        String ten = txtMaQuocGia.getText();
        String ma = txtTenQuocGia.getText();
        String id = "";
        if (trangThai == 1) {
            id = tsp.getQG(1).get(index).getId();
        } else {
            id = tsp.getQG(0).get(index).getId();
        }
        if (ten.isBlank() || ma.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Không được để trống thông tin");
        }
        QuocGia quocGia = new QuocGia(id, ma, ten, cbbQuocGia.getSelectedIndex());
        JOptionPane.showMessageDialog(rootPane, tsp.suaQG(quocGia));
        fillTable(tsp.getQG(1), modelTBL);
        fillTable(tsp.getQG(0), modelTBL1);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_btnChonActionPerformed

    private void btnChon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChon1ActionPerformed
        String ten = txtMaQuocGia.getText();
        String ma = txtTenQuocGia.getText();
        String id = "";
        if (trangThai == 1) {
            id = tsp.getQG(1).get(index).getId();
        } else {
            id = tsp.getQG(0).get(index).getId();
        }
        if (ten.isBlank() || ma.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Không được để trống thông tin");
        }
        QuocGia quocGia = new QuocGia(id, ma, ten, 0);
        JOptionPane.showMessageDialog(rootPane, tsp.suaQG(quocGia));
        fillTable(tsp.getQG(1), modelTBL);
        fillTable(tsp.getQG(0), modelTBL1);
    }//GEN-LAST:event_btnChon1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuocGiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuocGiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuocGiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuocGiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuocGiaView dialog = new QuocGiaView(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChon;
    private javax.swing.JButton btnChon1;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cbbQuocGia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblQuocGia1;
    private javax.swing.JTable tblQuocGia2;
    private javax.swing.JTextField txtMaQuocGia;
    private javax.swing.JTextField txtTenQuocGia;
    // End of variables declaration//GEN-END:variables
}
